#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrungTamNgoaiNgu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTTNN")]
	public partial class QLTTNNDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDanhSachPhongThi(DanhSachPhongThi instance);
    partial void UpdateDanhSachPhongThi(DanhSachPhongThi instance);
    partial void DeleteDanhSachPhongThi(DanhSachPhongThi instance);
    partial void InsertKhoaThi(KhoaThi instance);
    partial void UpdateKhoaThi(KhoaThi instance);
    partial void DeleteKhoaThi(KhoaThi instance);
    partial void InsertPhieuDangKy(PhieuDangKy instance);
    partial void UpdatePhieuDangKy(PhieuDangKy instance);
    partial void DeletePhieuDangKy(PhieuDangKy instance);
    partial void InsertPhongThi(PhongThi instance);
    partial void UpdatePhongThi(PhongThi instance);
    partial void DeletePhongThi(PhongThi instance);
    partial void InsertThiSinh(ThiSinh instance);
    partial void UpdateThiSinh(ThiSinh instance);
    partial void DeleteThiSinh(ThiSinh instance);
    #endregion
		
		public QLTTNNDataContext() : 
				base(global::TrungTamNgoaiNgu.Properties.Settings.Default.QLTTNNConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLTTNNDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTTNNDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTTNNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTTNNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DanhSachPhongThi> DanhSachPhongThis
		{
			get
			{
				return this.GetTable<DanhSachPhongThi>();
			}
		}
		
		public System.Data.Linq.Table<KhoaThi> KhoaThis
		{
			get
			{
				return this.GetTable<KhoaThi>();
			}
		}
		
		public System.Data.Linq.Table<PhieuDangKy> PhieuDangKies
		{
			get
			{
				return this.GetTable<PhieuDangKy>();
			}
		}
		
		public System.Data.Linq.Table<PhongThi> PhongThis
		{
			get
			{
				return this.GetTable<PhongThi>();
			}
		}
		
		public System.Data.Linq.Table<ThiSinh> ThiSinhs
		{
			get
			{
				return this.GetTable<ThiSinh>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhSachPhongThi")]
	public partial class DanhSachPhongThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_ThiSinh;
		
		private int _Id_PhongThi;
		
		private string _SBD;
		
		private System.Nullable<double> _DiemNghe;
		
		private System.Nullable<double> _DiemNoi;
		
		private System.Nullable<double> _DiemDoc;
		
		private System.Nullable<double> _DiemViet;
		
		private EntityRef<PhongThi> _PhongThi;
		
		private EntityRef<ThiSinh> _ThiSinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_ThiSinhChanging(int value);
    partial void OnId_ThiSinhChanged();
    partial void OnId_PhongThiChanging(int value);
    partial void OnId_PhongThiChanged();
    partial void OnSBDChanging(string value);
    partial void OnSBDChanged();
    partial void OnDiemNgheChanging(System.Nullable<double> value);
    partial void OnDiemNgheChanged();
    partial void OnDiemNoiChanging(System.Nullable<double> value);
    partial void OnDiemNoiChanged();
    partial void OnDiemDocChanging(System.Nullable<double> value);
    partial void OnDiemDocChanged();
    partial void OnDiemVietChanging(System.Nullable<double> value);
    partial void OnDiemVietChanged();
    #endregion
		
		public DanhSachPhongThi()
		{
			this._PhongThi = default(EntityRef<PhongThi>);
			this._ThiSinh = default(EntityRef<ThiSinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_ThiSinh", DbType="Int NOT NULL")]
		public int Id_ThiSinh
		{
			get
			{
				return this._Id_ThiSinh;
			}
			set
			{
				if ((this._Id_ThiSinh != value))
				{
					if (this._ThiSinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_ThiSinhChanging(value);
					this.SendPropertyChanging();
					this._Id_ThiSinh = value;
					this.SendPropertyChanged("Id_ThiSinh");
					this.OnId_ThiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_PhongThi", DbType="Int NOT NULL")]
		public int Id_PhongThi
		{
			get
			{
				return this._Id_PhongThi;
			}
			set
			{
				if ((this._Id_PhongThi != value))
				{
					if (this._PhongThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_PhongThiChanging(value);
					this.SendPropertyChanging();
					this._Id_PhongThi = value;
					this.SendPropertyChanged("Id_PhongThi");
					this.OnId_PhongThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SBD", DbType="VarChar(8)")]
		public string SBD
		{
			get
			{
				return this._SBD;
			}
			set
			{
				if ((this._SBD != value))
				{
					this.OnSBDChanging(value);
					this.SendPropertyChanging();
					this._SBD = value;
					this.SendPropertyChanged("SBD");
					this.OnSBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemNghe", DbType="Float")]
		public System.Nullable<double> DiemNghe
		{
			get
			{
				return this._DiemNghe;
			}
			set
			{
				if ((this._DiemNghe != value))
				{
					this.OnDiemNgheChanging(value);
					this.SendPropertyChanging();
					this._DiemNghe = value;
					this.SendPropertyChanged("DiemNghe");
					this.OnDiemNgheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemNoi", DbType="Float")]
		public System.Nullable<double> DiemNoi
		{
			get
			{
				return this._DiemNoi;
			}
			set
			{
				if ((this._DiemNoi != value))
				{
					this.OnDiemNoiChanging(value);
					this.SendPropertyChanging();
					this._DiemNoi = value;
					this.SendPropertyChanged("DiemNoi");
					this.OnDiemNoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDoc", DbType="Float")]
		public System.Nullable<double> DiemDoc
		{
			get
			{
				return this._DiemDoc;
			}
			set
			{
				if ((this._DiemDoc != value))
				{
					this.OnDiemDocChanging(value);
					this.SendPropertyChanging();
					this._DiemDoc = value;
					this.SendPropertyChanged("DiemDoc");
					this.OnDiemDocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemViet", DbType="Float")]
		public System.Nullable<double> DiemViet
		{
			get
			{
				return this._DiemViet;
			}
			set
			{
				if ((this._DiemViet != value))
				{
					this.OnDiemVietChanging(value);
					this.SendPropertyChanging();
					this._DiemViet = value;
					this.SendPropertyChanged("DiemViet");
					this.OnDiemVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThi_DanhSachPhongThi", Storage="_PhongThi", ThisKey="Id_PhongThi", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public PhongThi PhongThi
		{
			get
			{
				return this._PhongThi.Entity;
			}
			set
			{
				PhongThi previousValue = this._PhongThi.Entity;
				if (((previousValue != value) 
							|| (this._PhongThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongThi.Entity = null;
						previousValue.DanhSachPhongThis.Remove(this);
					}
					this._PhongThi.Entity = value;
					if ((value != null))
					{
						value.DanhSachPhongThis.Add(this);
						this._Id_PhongThi = value.Id;
					}
					else
					{
						this._Id_PhongThi = default(int);
					}
					this.SendPropertyChanged("PhongThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThiSinh_DanhSachPhongThi", Storage="_ThiSinh", ThisKey="Id_ThiSinh", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public ThiSinh ThiSinh
		{
			get
			{
				return this._ThiSinh.Entity;
			}
			set
			{
				ThiSinh previousValue = this._ThiSinh.Entity;
				if (((previousValue != value) 
							|| (this._ThiSinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThiSinh.Entity = null;
						previousValue.DanhSachPhongThis.Remove(this);
					}
					this._ThiSinh.Entity = value;
					if ((value != null))
					{
						value.DanhSachPhongThis.Add(this);
						this._Id_ThiSinh = value.Id;
					}
					else
					{
						this._Id_ThiSinh = default(int);
					}
					this.SendPropertyChanged("ThiSinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoaThi")]
	public partial class KhoaThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenKhoaThi;
		
		private System.DateTime _NgayThi;
		
		private EntitySet<PhieuDangKy> _PhieuDangKies;
		
		private EntitySet<PhongThi> _PhongThis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenKhoaThiChanging(string value);
    partial void OnTenKhoaThiChanged();
    partial void OnNgayThiChanging(System.DateTime value);
    partial void OnNgayThiChanged();
    #endregion
		
		public KhoaThi()
		{
			this._PhieuDangKies = new EntitySet<PhieuDangKy>(new Action<PhieuDangKy>(this.attach_PhieuDangKies), new Action<PhieuDangKy>(this.detach_PhieuDangKies));
			this._PhongThis = new EntitySet<PhongThi>(new Action<PhongThi>(this.attach_PhongThis), new Action<PhongThi>(this.detach_PhongThis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoaThi", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TenKhoaThi
		{
			get
			{
				return this._TenKhoaThi;
			}
			set
			{
				if ((this._TenKhoaThi != value))
				{
					this.OnTenKhoaThiChanging(value);
					this.SendPropertyChanging();
					this._TenKhoaThi = value;
					this.SendPropertyChanged("TenKhoaThi");
					this.OnTenKhoaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="Date NOT NULL")]
		public System.DateTime NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaThi_PhieuDangKy", Storage="_PhieuDangKies", ThisKey="Id", OtherKey="Id_KhoaThi")]
		public EntitySet<PhieuDangKy> PhieuDangKies
		{
			get
			{
				return this._PhieuDangKies;
			}
			set
			{
				this._PhieuDangKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaThi_PhongThi", Storage="_PhongThis", ThisKey="Id", OtherKey="ID_KhoaThi")]
		public EntitySet<PhongThi> PhongThis
		{
			get
			{
				return this._PhongThis;
			}
			set
			{
				this._PhongThis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDangKies(PhieuDangKy entity)
		{
			this.SendPropertyChanging();
			entity.KhoaThi = this;
		}
		
		private void detach_PhieuDangKies(PhieuDangKy entity)
		{
			this.SendPropertyChanging();
			entity.KhoaThi = null;
		}
		
		private void attach_PhongThis(PhongThi entity)
		{
			this.SendPropertyChanging();
			entity.KhoaThi = this;
		}
		
		private void detach_PhongThis(PhongThi entity)
		{
			this.SendPropertyChanging();
			entity.KhoaThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuDangKy")]
	public partial class PhieuDangKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_ThiSinh;
		
		private int _Id_KhoaThi;
		
		private string _TrinhDo;
		
		private System.DateTime _NgayDangKy;
		
		private EntityRef<KhoaThi> _KhoaThi;
		
		private EntityRef<ThiSinh> _ThiSinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_ThiSinhChanging(int value);
    partial void OnId_ThiSinhChanged();
    partial void OnId_KhoaThiChanging(int value);
    partial void OnId_KhoaThiChanged();
    partial void OnTrinhDoChanging(string value);
    partial void OnTrinhDoChanged();
    partial void OnNgayDangKyChanging(System.DateTime value);
    partial void OnNgayDangKyChanged();
    #endregion
		
		public PhieuDangKy()
		{
			this._KhoaThi = default(EntityRef<KhoaThi>);
			this._ThiSinh = default(EntityRef<ThiSinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_ThiSinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_ThiSinh
		{
			get
			{
				return this._Id_ThiSinh;
			}
			set
			{
				if ((this._Id_ThiSinh != value))
				{
					if (this._ThiSinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_ThiSinhChanging(value);
					this.SendPropertyChanging();
					this._Id_ThiSinh = value;
					this.SendPropertyChanged("Id_ThiSinh");
					this.OnId_ThiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_KhoaThi", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_KhoaThi
		{
			get
			{
				return this._Id_KhoaThi;
			}
			set
			{
				if ((this._Id_KhoaThi != value))
				{
					if (this._KhoaThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_KhoaThiChanging(value);
					this.SendPropertyChanging();
					this._Id_KhoaThi = value;
					this.SendPropertyChanged("Id_KhoaThi");
					this.OnId_KhoaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDo", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string TrinhDo
		{
			get
			{
				return this._TrinhDo;
			}
			set
			{
				if ((this._TrinhDo != value))
				{
					this.OnTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._TrinhDo = value;
					this.SendPropertyChanged("TrinhDo");
					this.OnTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="Date NOT NULL")]
		public System.DateTime NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this.OnNgayDangKyChanging(value);
					this.SendPropertyChanging();
					this._NgayDangKy = value;
					this.SendPropertyChanged("NgayDangKy");
					this.OnNgayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaThi_PhieuDangKy", Storage="_KhoaThi", ThisKey="Id_KhoaThi", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public KhoaThi KhoaThi
		{
			get
			{
				return this._KhoaThi.Entity;
			}
			set
			{
				KhoaThi previousValue = this._KhoaThi.Entity;
				if (((previousValue != value) 
							|| (this._KhoaThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoaThi.Entity = null;
						previousValue.PhieuDangKies.Remove(this);
					}
					this._KhoaThi.Entity = value;
					if ((value != null))
					{
						value.PhieuDangKies.Add(this);
						this._Id_KhoaThi = value.Id;
					}
					else
					{
						this._Id_KhoaThi = default(int);
					}
					this.SendPropertyChanged("KhoaThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThiSinh_PhieuDangKy", Storage="_ThiSinh", ThisKey="Id_ThiSinh", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public ThiSinh ThiSinh
		{
			get
			{
				return this._ThiSinh.Entity;
			}
			set
			{
				ThiSinh previousValue = this._ThiSinh.Entity;
				if (((previousValue != value) 
							|| (this._ThiSinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThiSinh.Entity = null;
						previousValue.PhieuDangKies.Remove(this);
					}
					this._ThiSinh.Entity = value;
					if ((value != null))
					{
						value.PhieuDangKies.Add(this);
						this._Id_ThiSinh = value.Id;
					}
					else
					{
						this._Id_ThiSinh = default(int);
					}
					this.SendPropertyChanged("ThiSinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongThi")]
	public partial class PhongThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TenPhongThi;
		
		private string _TrinhDo;
		
		private string _CaThi;
		
		private int _ID_KhoaThi;
		
		private EntitySet<DanhSachPhongThi> _DanhSachPhongThis;
		
		private EntityRef<KhoaThi> _KhoaThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenPhongThiChanging(string value);
    partial void OnTenPhongThiChanged();
    partial void OnTrinhDoChanging(string value);
    partial void OnTrinhDoChanged();
    partial void OnCaThiChanging(string value);
    partial void OnCaThiChanged();
    partial void OnID_KhoaThiChanging(int value);
    partial void OnID_KhoaThiChanged();
    #endregion
		
		public PhongThi()
		{
			this._DanhSachPhongThis = new EntitySet<DanhSachPhongThi>(new Action<DanhSachPhongThi>(this.attach_DanhSachPhongThis), new Action<DanhSachPhongThi>(this.detach_DanhSachPhongThis));
			this._KhoaThi = default(EntityRef<KhoaThi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongThi", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TenPhongThi
		{
			get
			{
				return this._TenPhongThi;
			}
			set
			{
				if ((this._TenPhongThi != value))
				{
					this.OnTenPhongThiChanging(value);
					this.SendPropertyChanging();
					this._TenPhongThi = value;
					this.SendPropertyChanged("TenPhongThi");
					this.OnTenPhongThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDo", DbType="VarChar(2)")]
		public string TrinhDo
		{
			get
			{
				return this._TrinhDo;
			}
			set
			{
				if ((this._TrinhDo != value))
				{
					this.OnTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._TrinhDo = value;
					this.SendPropertyChanged("TrinhDo");
					this.OnTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaThi", DbType="NVarChar(8)")]
		public string CaThi
		{
			get
			{
				return this._CaThi;
			}
			set
			{
				if ((this._CaThi != value))
				{
					this.OnCaThiChanging(value);
					this.SendPropertyChanging();
					this._CaThi = value;
					this.SendPropertyChanged("CaThi");
					this.OnCaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KhoaThi", DbType="Int NOT NULL")]
		public int ID_KhoaThi
		{
			get
			{
				return this._ID_KhoaThi;
			}
			set
			{
				if ((this._ID_KhoaThi != value))
				{
					if (this._KhoaThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KhoaThiChanging(value);
					this.SendPropertyChanging();
					this._ID_KhoaThi = value;
					this.SendPropertyChanged("ID_KhoaThi");
					this.OnID_KhoaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThi_DanhSachPhongThi", Storage="_DanhSachPhongThis", ThisKey="Id", OtherKey="Id_PhongThi")]
		public EntitySet<DanhSachPhongThi> DanhSachPhongThis
		{
			get
			{
				return this._DanhSachPhongThis;
			}
			set
			{
				this._DanhSachPhongThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaThi_PhongThi", Storage="_KhoaThi", ThisKey="ID_KhoaThi", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public KhoaThi KhoaThi
		{
			get
			{
				return this._KhoaThi.Entity;
			}
			set
			{
				KhoaThi previousValue = this._KhoaThi.Entity;
				if (((previousValue != value) 
							|| (this._KhoaThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoaThi.Entity = null;
						previousValue.PhongThis.Remove(this);
					}
					this._KhoaThi.Entity = value;
					if ((value != null))
					{
						value.PhongThis.Add(this);
						this._ID_KhoaThi = value.Id;
					}
					else
					{
						this._ID_KhoaThi = default(int);
					}
					this.SendPropertyChanged("KhoaThi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhSachPhongThis(DanhSachPhongThi entity)
		{
			this.SendPropertyChanging();
			entity.PhongThi = this;
		}
		
		private void detach_DanhSachPhongThis(DanhSachPhongThi entity)
		{
			this.SendPropertyChanging();
			entity.PhongThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThiSinh")]
	public partial class ThiSinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CMND;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _NoiSinh;
		
		private System.DateTime _NgayCap;
		
		private string _NoiCap;
		
		private string _SDT;
		
		private string _Email;
		
		private EntitySet<DanhSachPhongThi> _DanhSachPhongThis;
		
		private EntitySet<PhieuDangKy> _PhieuDangKies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnNoiSinhChanging(string value);
    partial void OnNoiSinhChanged();
    partial void OnNgayCapChanging(System.DateTime value);
    partial void OnNgayCapChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public ThiSinh()
		{
			this._DanhSachPhongThis = new EntitySet<DanhSachPhongThi>(new Action<DanhSachPhongThi>(this.attach_DanhSachPhongThis), new Action<DanhSachPhongThi>(this.detach_DanhSachPhongThis));
			this._PhieuDangKies = new EntitySet<PhieuDangKy>(new Action<PhieuDangKy>(this.attach_PhieuDangKies), new Action<PhieuDangKy>(this.detach_PhieuDangKies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NChar(12) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiSinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NoiSinh
		{
			get
			{
				return this._NoiSinh;
			}
			set
			{
				if ((this._NoiSinh != value))
				{
					this.OnNoiSinhChanging(value);
					this.SendPropertyChanging();
					this._NoiSinh = value;
					this.SendPropertyChanged("NoiSinh");
					this.OnNoiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="Date NOT NULL")]
		public System.DateTime NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(12) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(40) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThiSinh_DanhSachPhongThi", Storage="_DanhSachPhongThis", ThisKey="Id", OtherKey="Id_ThiSinh")]
		public EntitySet<DanhSachPhongThi> DanhSachPhongThis
		{
			get
			{
				return this._DanhSachPhongThis;
			}
			set
			{
				this._DanhSachPhongThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThiSinh_PhieuDangKy", Storage="_PhieuDangKies", ThisKey="Id", OtherKey="Id_ThiSinh")]
		public EntitySet<PhieuDangKy> PhieuDangKies
		{
			get
			{
				return this._PhieuDangKies;
			}
			set
			{
				this._PhieuDangKies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DanhSachPhongThis(DanhSachPhongThi entity)
		{
			this.SendPropertyChanging();
			entity.ThiSinh = this;
		}
		
		private void detach_DanhSachPhongThis(DanhSachPhongThi entity)
		{
			this.SendPropertyChanging();
			entity.ThiSinh = null;
		}
		
		private void attach_PhieuDangKies(PhieuDangKy entity)
		{
			this.SendPropertyChanging();
			entity.ThiSinh = this;
		}
		
		private void detach_PhieuDangKies(PhieuDangKy entity)
		{
			this.SendPropertyChanging();
			entity.ThiSinh = null;
		}
	}
}
#pragma warning restore 1591
